# Generated by Django 3.0.3 on 2020-03-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='media')),
                ('heading', models.CharField(default='', max_length=50)),
                ('discription', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(default='', max_length=50)),
                ('School', models.TextField(blank=True, default='')),
                ('Session', models.CharField(default='', max_length=20)),
                ('Result', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='', upload_to='media/gallery')),
            ],
        ),
    ]
